package scenario

import "errors"

var (
	ErrEmptyStartNodeID       = errors.New("empty start node ID")
	ErrUnknownStartNode       = errors.New("unknown start node")
	ErrEmptyNodeID            = errors.New("empty node ID")
	ErrEmptyNodeText          = errors.New("empty node text")
	ErrDuplicateNodeID        = errors.New("duplicate node ID")
	ErrEmptyEndingID          = errors.New("empty ending ID")
	ErrEmptyEndingHeader      = errors.New("empty ending header")
	ErrEmptyEndingResult      = errors.New("empty ending result")
	ErrDuplicateEndingID      = errors.New("duplicate ending ID")
	ErrEmptyChoiceID          = errors.New("empty choice ID")
	ErrEmptyChoiceText        = errors.New("empty choice text")
	ErrEmptyConsequence       = errors.New("empty choice consequence")
	ErrEmptyExplanation       = errors.New("empty choice explanation")
	ErrDuplicateChoiceID      = errors.New("duplicate choice ID")
	ErrTooFewNodeChoices      = errors.New("node has fewer than four choices")
	ErrInvalidChoiceTarget    = errors.New("choice must have exactly one target")
	ErrUnknownNode            = errors.New("unknown node")
	ErrUnknownEnding          = errors.New("unknown ending")
	ErrInvalidWeight          = errors.New("invalid weight")
	ErrInvalidScore           = errors.New("invalid score")
	ErrMissingRiskCategory    = errors.New("missing risk category")
	ErrUnknownRiskCategory    = errors.New("unknown risk category")
	ErrCycleDetected          = errors.New("cycle detected")
	ErrUnreachableNode        = errors.New("unreachable node")
	ErrUnreachableEnding      = errors.New("unreachable ending")
	ErrTooFewReachableEndings = errors.New("too few reachable endings")
	ErrPathTooShort           = errors.New("scenario path has fewer than three choices")
	ErrPathWithoutBranching   = errors.New("scenario path has no branching")
)
